import React from 'react';

import Style from './About.scss';

/**
 * The content of the about page.
 */
export default class About extends React.Component
{
    render()
    {
        return (
            <div className={Style.About}>
                <p className={Style.Text}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed velit in lorem consectetur sollicitudin. In malesuada ligula sed eros facilisis consectetur. Proin ultricies mi nunc, id imperdiet dolor lobortis in. Nullam fringilla semper tellus, sit amet faucibus velit condimentum tristique. Suspendisse potenti. Proin volutpat placerat magna quis congue. Sed dapibus diam nec arcu iaculis vestibulum. Pellentesque luctus tellus sit amet posuere dictum. Phasellus et porttitor elit, ut convallis enim. Nullam mollis mi eget nisl luctus convallis. Etiam maximus erat ut ipsum vulputate, id convallis enim consectetur. Donec at ligula ut magna ultrices pellentesque. Nam lectus orci, laoreet eget sagittis quis, facilisis ullamcorper nulla.</p>
                <p className={Style.Text}>Nam malesuada ornare massa, id molestie sapien porta id. Fusce pretium aliquam nulla vel semper. Quisque quis felis dolor. Pellentesque ac dolor eros. Curabitur ut scelerisque arcu. Nulla at enim rhoncus, tempus sapien consequat, viverra dolor. In enim nulla, sagittis id feugiat feugiat, pulvinar venenatis ex. Nulla quis tincidunt ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque posuere ligula sem, venenatis gravida elit fermentum tincidunt. Nullam nec eros malesuada, malesuada erat sit amet, fringilla nunc. Donec vehicula odio turpis, ut imperdiet ligula rutrum in. Donec pulvinar faucibus elit, in gravida est. Proin at sapien nibh.</p>
                <p className={Style.Text}>Cras facilisis odio ut nulla auctor euismod. Proin mattis justo nisl, ut tristique arcu faucibus vulputate. Donec arcu neque, elementum vitae elementum at, mattis at ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc interdum nunc at turpis posuere, eget iaculis elit ultricies. Suspendisse magna odio, facilisis id eros id, iaculis fermentum ipsum. Mauris neque eros, interdum et sapien ac, tempus varius urna. Cras pharetra tempus nibh. Nunc quis elementum urna. Fusce sollicitudin lorem euismod vehicula vehicula. Nam mollis, massa nec suscipit faucibus, urna mauris accumsan libero, ut consequat augue lacus non tortor. Nulla fermentum tortor eget elit cursus, ac suscipit nibh placerat. Vivamus luctus tempus diam, sit amet viverra orci. Nam tempor libero at purus imperdiet, eget interdum turpis facilisis. Vivamus ornare condimentum mollis.</p>
                <p className={Style.Text}>Vivamus eget quam at leo blandit malesuada. Etiam aliquam rutrum tortor. Nam bibendum, orci sollicitudin rhoncus egestas, nisl justo congue dolor, vel luctus augue magna sit amet elit. Vivamus nec accumsan ipsum. Vestibulum vel mattis nunc, gravida bibendum arcu. Quisque efficitur turpis pharetra mi euismod convallis. Nam ornare, nulla ac ultrices tincidunt, odio mi rutrum massa, nec tincidunt risus nisi eu turpis. Maecenas commodo urna in ornare bibendum. Donec tempus, turpis ut vestibulum elementum, lectus eros ullamcorper massa, ac posuere sem risus ac enim. Suspendisse lacinia consectetur odio vitae lobortis. Aliquam pharetra erat id felis pellentesque, sed efficitur lorem sagittis. Ut at mauris eu lorem imperdiet varius. Sed posuere, est vel elementum posuere, sapien nunc convallis nisi, et ornare ipsum enim quis mi. Sed porta scelerisque ex eu fringilla. Mauris sollicitudin sodales ipsum, consectetur tincidunt elit aliquam eu.</p>
                <p className={Style.Text}>Donec augue enim, feugiat id gravida id, dictum in justo. Vestibulum tempor, enim imperdiet dapibus placerat, magna ex pellentesque magna, id porttitor purus sem ut tellus. Etiam rutrum nunc id ornare condimentum. Integer rhoncus, purus ultrices dignissim luctus, nisi arcu porttitor felis, quis condimentum quam massa vitae quam. Nunc fermentum, nisl cursus congue convallis, purus ipsum laoreet ex, ac dignissim sapien enim quis quam. Aliquam convallis, dolor ut pharetra vulputate, purus nibh elementum enim, et pretium arcu magna ut tortor. Vestibulum eget massa mattis, convallis libero sit amet, tincidunt enim. Phasellus enim sem, ullamcorper ac fringilla ut, laoreet in libero. Pellentesque sit amet elementum lectus. Proin eu pretium risus. Sed vulputate, dui eu mattis efficitur, velit neque elementum massa, et convallis lacus dui eget nunc. Quisque blandit rutrum imperdiet. Vivamus vitae sem elementum, consectetur ligula a, egestas metus. Pellentesque libero turpis, aliquet in lacus at, aliquet porttitor ante. Aliquam lacinia massa lectus, et dictum enim lobortis ut. Aliquam vitae ipsum convallis, blandit augue vitae, bibendum risus.</p>
            </div>
        );
    }
}